name: foliate
grade: stable
adopt-info: foliate
license: GPL-3.0+

base: core22
confinement: strict

apps:
  foliate:
    command: usr/bin/com.github.johnfactotum.Foliate
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - removable-media
    slots:
      - dbus-daemon
    common-id: com.github.johnfactotum.Foliate

parts:
  foliate:
    plugin: meson
    source: .
    override-pull: |
      craftctl default
      sed -i -e 's|@GJS@|/usr/bin/gjs|g' src/com.github.johnfactotum.Foliate.in
      craftctl set-version $(git describe --tags --abbrev=10)
    override-build: |
      set -ex
      xmlstarlet edit -L -u "/schemalist/schema/key[@name='tts-command']/default" -v "'espeak-ng -v mb-en1'" $CRAFT_PART_BUILD/data/com.github.johnfactotum.Foliate.gschema.xml
      craftctl default
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    build-packages:
      - git # for set-version
      - xmlstarlet  # for override-build
    organize:
      snap/foliate/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.johnfactotum.Foliate.appdata.xml]
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - mbrola-en1
      - mbrola

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data
  # This is a bind instead of a (faster) symlink because mbrola uses LD_PRELOAD
  # with libraries from this directory, which doesn't work with symlinks.
  /usr/lib/$CRAFT_ARCH_TRIPLET/mbrola:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/mbrola
  /usr/share/mbrola:
    symlink: $SNAP/usr/share/mbrola
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs
