name: foliate
grade: stable
adopt-info: foliate
version: 3.0.0
description: A simple and modern GTK e-book reader
license: GPL-3.0+
base: core22
confinement: strict
compression: lzo
architectures:
- build-on: amd64
layout:
  /usr/lib/webkitgtk-6.0:
    bind: $SNAP/webkitgtk/usr/lib/webkitgtk-6.0
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs
slots:
  foliate:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate
plugs:
  webkitgtk:
    interface: content
    target: $SNAP/webkitgtk
    default-provider: webkitgtk
apps:
  foliate:
    command: usr/bin/foliate
    extensions:
    - gnome
    plugs:
    - home
    - network
    - audio-playback
    - removable-media
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop
    common-id: com.github.johnfactotum.Foliate
    environment:
      LD_LIBRARY_PATH: $SNAP/webkitgtk/usr/lib:$SNAP/webkitgtk/usr/lib/$CRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0:$SNAP/webkitgtk/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0
parts:
  foliate:
    plugin: meson
    source: https://github.com/johnfactotum/foliate.git
    source-branch: gtk4
    meson-parameters:
    - --prefix=/snap/foliate/current/usr
    override-pull: |
      craftctl default
      sed -i '1c#!/usr/bin/gjs -m' src/main.js
    build-packages:
    - xmlstarlet
    build-snaps:
    - webkitgtk-sdk/latest/edge
    parse-info:
    - usr/share/metainfo/com.github.johnfactotum.Foliate.metainfo.xml
    organize:
      snap/foliate/current/usr: usrname: foliate
grade: stable
adopt-info: foliate
license: GPL-3.0+
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  
layout:
  /usr/lib/webkitgtk-6.0:
    bind: $SNAP/webkitgtk/usr/lib/webkitgtk-6.0
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs

slots:
  foliate:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate
plugs:
  webkitgtk:
    interface: content
    target: $SNAP/webkitgtk
    default-provider: webkitgtk
    
apps:
  foliate:
    command: usr/bin/foliate
    extensions: [gnome]
    plugs:
      - home
      - network
      - audio-playback
      - removable-media
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop
    common-id: com.github.johnfactotum.Foliate
    environment:
      GI_TYPELIB_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/girepository-1.0:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/gjs/girepository-1.0

parts:
  foliate:
    plugin: meson
    source: .
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    override-pull: |
      craftctl default
      sed -i -e 's|@GJS@|/usr/bin/gjs|g' src/com.github.johnfactotum.Foliate.in
    build-packages:
      - xmlstarlet 
    build-snaps:
      - webkitgtk-sdk/latest/edge
    parse-info: [usr/share/metainfo/com.github.johnfactotum.Foliate.metainfo.xml]
    organize:
      snap/foliate/current/usr: usr
      
