import Gtk from 'gi://Gtk'
import Gio from 'gi://Gio'
import GObject from 'gi://GObject'
import WebKit from 'gi://WebKit'
import Gdk from 'gi://Gdk'
import GLib from 'gi://GLib'
import { gettext as _ } from 'gettext'

import * as utils from './utils.js'
import { WebView } from './webview.js'
import { locales, matchLocales } from './format.js'
import { loadPrompts, getDefaultPrompt, appendToFile } from './ai-prompts.js'

const getLanguage = lang => {
    try {
        return new Intl.Locale(lang).language
    } catch (e) {
        console.warn(e)
        return 'en'
    }
}

const getGoogleTranslateLanguages = utils.memoize(() => {
    // list of languages supported by Google Translate
    // generated by running the following on https://cloud.google.com/translate/docs/languages
    // [...document.querySelector('table').querySelectorAll('tr')].map(tr => tr.querySelector('code')?.innerText).filter(x => x).map(x => `'${x}'`).join(', ')
    const displayName = new Intl.DisplayNames(locales, { type: 'language' })
    const langs = ['af', 'sq', 'am', 'ar', 'hy', 'as', 'ay', 'az', 'bm', 'eu', 'be', 'bn', 'bho', 'bs', 'bg', 'ca', 'ceb', 'zh-CN', 'zh-TW', 'co', 'hr', 'cs', 'da', 'dv', 'doi', 'nl', 'en', 'eo', 'et', 'ee', 'fil', 'fi', 'fr', 'fy', 'gl', 'ka', 'de', 'el', 'gn', 'gu', 'ht', 'ha', 'haw', 'he', 'hi', 'hmn', 'hu', 'is', 'ig', 'ilo', 'id', 'ga', 'it', 'ja', 'jv', 'kn', 'kk', 'km', 'rw', 'gom', 'ko', 'kri', 'ku', 'ckb', 'ky', 'lo', 'la', 'lv', 'ln', 'lt', 'lg', 'lb', 'mk', 'mai', 'mg', 'ms', 'ml', 'mt', 'mi', 'mr', 'mni-Mtei', 'lus', 'mn', 'my', 'ne', 'no', 'ny', 'or', 'om', 'ps', 'fa', 'pl', 'pt', 'pa', 'qu', 'ro', 'ru', 'sm', 'sa', 'gd', 'nso', 'sr', 'st', 'sn', 'sd', 'si', 'sk', 'sl', 'so', 'es', 'su', 'sw', 'sv', 'tl', 'tg', 'ta', 'tt', 'te', 'th', 'ti', 'ts', 'tr', 'tk', 'ak', 'uk', 'ur', 'ug', 'uz', 'vi', 'cy', 'xh', 'yi', 'yo', 'zu']
    const defaultLang = matchLocales(langs)[0] ?? 'en'
    return [langs.map(lang => [lang, displayName.of(lang)]), defaultLang]
})

const tools = {
    'dictionary': {
        label: _('Dictionary'),
        uri: 'foliate-selection-tool:///selection-tools/wiktionary.html',
        run: (__, { text, lang }) => ({
            msg: {
                footer: _('From <a id="link">Wiktionary</a>, released under the <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA License</a>.'),
                error: _('No Definitions Found'),
                errorAction: _('Search on Wiktionary'),
            },
            text,
            lang: getLanguage(lang),
        }),
    },
    'wikipedia': {
        label: _('Wikipedia'),
        uri: 'foliate-selection-tool:///selection-tools/wikipedia.html',
        run: (__, { text, lang }) => ({
            msg: {
                footer: _('From <a id="link">Wikipedia</a>, released under the <a href="https://en.wikipedia.org/wiki/Wikipedia:Text_of_the_Creative_Commons_Attribution-ShareAlike_4.0_International_License">CC BY-SA License</a>.'),
                error: _('No Definitions Found'),
                errorAction: _('Search on Wikipedia'),
            },
            text,
            lang: getLanguage(lang),
        }),
    },
    'translate': {
        label: _('Translate'),
        uri: 'foliate-selection-tool:///selection-tools/translate.html',
        run: (popover, { text }) => {
            const [langs, defaultLang] = getGoogleTranslateLanguages()
            return {
                msg: {
                    footer: _('Translation by Google Translate'),
                    error: _('Cannot retrieve translation'),
                    search: _('Search…'),
                    langs,
                },
                text,
                lang: popover.translate_target_language || defaultLang,
            }
        },
    },
    'ai-assistant': {
        label: _('Ask AI Assistant'),
        uri: 'foliate-selection-tool:///selection-tools/ai-assistant.html',
        run: (popover, { text }, promptOverride) => {
            // Read from GSettings directly as fallback when property bindings
            // haven't synced (e.g. empty string defaults from GObject)
            const s = utils.settings('viewer')
            const get = key => s?.get_string(key) || ''

            const provider = popover.ai_assistant_provider || get('ai-assistant-provider') || 'openai'
            const openaiKey = popover.ai_assistant_openai_key || get('ai-assistant-openai-key') || GLib.getenv('OPENAI_API_KEY') || ''
            const geminiKey = popover.ai_assistant_gemini_key || get('ai-assistant-gemini-key') || GLib.getenv('GEMINI_API_KEY') || ''
            const kiloKey = popover.ai_assistant_kilo_key || get('ai-assistant-kilo-key') || GLib.getenv('KILO_API_KEY') || ''

            // Priority: explicit override > default prompt from prompts file > GSettings > fallback
            let promptTemplate = promptOverride
            if (!promptTemplate) {
                const defaultPrompt = getDefaultPrompt(loadPrompts())
                promptTemplate = defaultPrompt?.prompt
                    || popover.ai_assistant_prompt_template
                    || get('ai-assistant-prompt-template')
                    || 'Explain the following text: {text}'
            }

            return {
                msg: {
                    footer: provider === 'gemini'
                        ? _('Powered by Google Gemini')
                        : provider === 'kilo'
                        ? _('Powered by Kilo (Kimi K2.5)')
                        : _('Powered by OpenAI ChatGPT'),
                    error: _('AI Request Failed'),
                    noApiKey: _('API Key Not Configured'),
                },
                text,
                provider,
                openaiKey,
                geminiKey,
                kiloKey,
                openaiModel: popover.ai_assistant_openai_model || get('ai-assistant-openai-model') || 'gpt-4o-mini',
                geminiModel: popover.ai_assistant_gemini_model || get('ai-assistant-gemini-model') || 'gemini-2.0-flash',
                kiloModel: popover.ai_assistant_kilo_model || get('ai-assistant-kilo-model') || 'moonshotai/kimi-k2.5',
                promptTemplate,
                enabled: popover.ai_assistant_enabled || (s?.get_boolean('ai-assistant-enabled') ?? true),
            }
        },
    },
}

const SelectionToolPopover = GObject.registerClass({
    GTypeName: 'FoliateSelectionToolPopover',
    Properties: utils.makeParams({
        'translate-target-language': 'string',
        'ai-assistant-enabled': 'boolean',
        'ai-assistant-provider': 'string',
        'ai-assistant-openai-key': 'string',
        'ai-assistant-gemini-key': 'string',
        'ai-assistant-kilo-key': 'string',
        'ai-assistant-openai-model': 'string',
        'ai-assistant-gemini-model': 'string',
        'ai-assistant-kilo-model': 'string',
        'ai-assistant-prompt-template': 'string',
    }),
}, class extends Gtk.Popover {
    #webView = utils.connect(new WebView({
        settings: new WebKit.Settings({
            enable_write_console_messages_to_stdout: true,
            enable_back_forward_navigation_gestures: false,
            enable_hyperlink_auditing: false,
            enable_html5_database: false,
            enable_html5_local_storage: false,
        }),
    }), {
        'decide-policy': (_, decision, type) => {
            switch (type) {
                case WebKit.PolicyDecisionType.NAVIGATION_ACTION:
                case WebKit.PolicyDecisionType.NEW_WINDOW_ACTION: {
                    const { uri } = decision.navigation_action.get_request()
                    if (!uri.startsWith('foliate-selection-tool:')) {
                        decision.ignore()
                        new Gtk.UriLauncher({ uri }).launch(this.root, null, null)
                        return true
                    }
                }
            }
        },
    })
    constructor(params) {
        super(params)
        // Allow cross-origin API requests from custom URI scheme
        this.#webView.set_cors_allowlist([
            'https://api.openai.com/*',
            'https://generativelanguage.googleapis.com/*',
            'https://api.kilo.ai/*',
        ])
        utils.bindSettings('viewer', this, [
            'translate-target-language',
            'ai-assistant-enabled',
            'ai-assistant-provider',
            'ai-assistant-openai-key',
            'ai-assistant-gemini-key',
            'ai-assistant-kilo-key',
            'ai-assistant-openai-model',
            'ai-assistant-gemini-model',
            'ai-assistant-kilo-model',
            'ai-assistant-prompt-template',
        ])
        Object.assign(this, {
            width_request: 300,
            height_request: 300,
        })
        this.child = this.#webView
        this.#webView.set_background_color(new Gdk.RGBA())
        this.#webView.registerHandler('settings', payload => {
            if (payload.key === 'translate-target-language')
                this.translate_target_language = payload.value
        })
        this.#webView.registerHandler('ai-result', payload => {
            if (this.#onResult) this.#onResult(payload)
        })
    }
    #onResult = null
    setOnResult(callback) {
        this.#onResult = callback
    }
    loadTool(tool, init) {
        this.#webView.loadURI(tool.uri)
            .then(() => this.#webView.opacity = 1)
            .then(() => this.#webView.exec('init', init))
            .catch(e => console.error(e))
    }
})

export const getSelectionToolPopover = utils.memoize(() => new SelectionToolPopover())

export const aiTool = tools['ai-assistant']

export const SelectionPopover = GObject.registerClass({
    GTypeName: 'FoliateSelectionPopover',
    Template: pkg.moduleuri('ui/selection-popover.ui'),
    Signals: {
        'show-popover': { param_types: [Gtk.Popover.$gtype] },
        'run-tool': { return_type: GObject.TYPE_JSOBJECT },
    },
}, class extends Gtk.PopoverMenu {
    constructor(params) {
        super(params)
        const model = this.menu_model
        const section = new Gio.Menu()
        model.insert_section(1, null, section)

        const group = new Gio.SimpleActionGroup()
        this.insert_action_group('selection-tools', group)

        const prompts = loadPrompts()

        for (const [name, tool] of Object.entries(tools)) {
            // For the AI assistant, if multiple prompts exist, add individual prompt items
            if (name === 'ai-assistant' && prompts.length > 1) {
                const aiSection = new Gio.Menu()
                for (const prompt of prompts) {
                    const actionName = `ai-prompt-${prompt.id}`
                    const action = new Gio.SimpleAction({ name: actionName })
                    action.connect('activate', () => {
                        const popover = getSelectionToolPopover()
                        const toolData = this.emit('run-tool')
                        const init = tool.run(popover, toolData, prompt.prompt)
                        if (prompt.outputFile) {
                            popover.setOnResult(({ result }) =>
                                appendToFile(prompt.outputFile, toolData.text, result))
                        } else {
                            popover.setOnResult(null)
                        }
                        popover.loadTool(tool, init)
                        this.emit('show-popover', popover)
                    })
                    group.add_action(action)
                    const label = prompt.isDefault
                        ? `${prompt.name} ★`
                        : prompt.name
                    aiSection.append(label, `selection-tools.${actionName}`)
                }
                section.append_submenu(_('Ask AI Assistant'), aiSection)
                continue
            }

            const action = new Gio.SimpleAction({ name })
            action.connect('activate', () => {
                const popover = getSelectionToolPopover()
                const toolData = this.emit('run-tool')
                // For ai-assistant with single/default prompt, handle file append
                if (name === 'ai-assistant') {
                    const defaultPrompt = getDefaultPrompt(prompts)
                    if (defaultPrompt?.outputFile) {
                        popover.setOnResult(({ result }) =>
                            appendToFile(defaultPrompt.outputFile, toolData.text, result))
                    } else {
                        popover.setOnResult(null)
                    }
                }
                Promise.resolve(tool.run(popover, toolData))
                    .then(x => popover.loadTool(tool, x))
                    .catch(e => console.error(e))
                this.emit('show-popover', popover)
            })
            group.add_action(action)
            section.append(tool.label, `selection-tools.${name}`)
        }

        // Intercept keyboard shortcuts for AI prompts while popover is open
        const promptAccels = []
        for (const prompt of prompts) {
            if (!prompt.shortcut) continue
            const [ok, keyval, mods] = Gtk.accelerator_parse(prompt.shortcut)
            if (!ok) continue
            const actionName = prompts.length > 1
                ? `ai-prompt-${prompt.id}` : 'ai-assistant'
            promptAccels.push({ keyval, mods, actionName })
        }
        if (promptAccels.length) {
            const keyCtrl = new Gtk.EventControllerKey({
                propagation_phase: Gtk.PropagationPhase.CAPTURE,
            })
            keyCtrl.connect('key-pressed', (_, keyval, keycode, state) => {
                const mods = state & Gtk.accelerator_get_default_mod_mask()
                for (const accel of promptAccels) {
                    if (keyval === accel.keyval && mods === accel.mods) {
                        this.popdown()
                        group.activate_action(accel.actionName, null)
                        return true
                    }
                }
                return false
            })
            this.add_controller(keyCtrl)
        }
    }
})
