# This is a basic workflow to help you get started with Actions

name: Build Debian Package

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ gtk4 ]
  pull_request:
    branches: [ gtk4 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - run: sudo apt install build-essential debhelper meson gettext pkg-config libglib2.0-dev gjs appstream libgjs-dev libgtk-4-dev libadwaita-1-dev libwebkitgtk-6.0-dev desktop-file-utils
      - run: dpkg-buildpackage -us -uc -nc
      - run: mv ../*.deb .
      - uses: actions/upload-artifact@v4
        with:
          name: Debian Package
          path: "*.deb"
